package com.didispace.entity;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.role_id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    private Integer roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.passwd
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
     * @return  the value of user.name
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
     * @param name  the value for user.name
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.role_id
     * @return  the value of user.role_id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.role_id
     * @param roleId  the value for user.role_id
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.passwd
     * @return  the value of user.passwd
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.passwd
     * @param passwd  the value for user.passwd
     * @mbg.generated  Fri Jun 07 01:47:44 CST 2019
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}