package com.didispace.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.didispace.entity.House;

@Mapper
public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    House selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue May 21 15:12:45 CST 2019
     */
    int updateByPrimaryKey(House record);
}